/*
 * Rustで例外処理。
 * CreatedAt: 2019-06-26
 */
fn main() {
    panic!("Error !!");
}

